[package]
name = "rust_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
hashsig = { git = "https://github.com/b-wagn/hash-sig", branch = "main" }
p3-koala-bear = { git = "https://github.com/Plonky3/Plonky3", rev = "2117e4b" }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3", rev = "2117e4b" }
p3-field = { git = "https://github.com/Plonky3/Plonky3", rev = "2117e4b" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3", rev = "2117e4b" }
rand = { version = "0.9", features = ["std_rng"] }
rand_chacha = "0.9"
sha3 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
bincode = "1.3"
num-bigint = "0.4"
num-traits = "0.2"

[[bin]]
name = "keygen_bench"
path = "src/main.rs"

[[bin]]
name = "test_internal"
path = "src/test_internal.rs"

[[bin]]
name = "sign_message"
path = "src/sign_message.rs"

[[bin]]
name = "verify_signature"
path = "src/verify_signature.rs"

[[bin]]
name = "sign_message_2_18"
path = "src/sign_message_2_18.rs"

[[bin]]
name = "verify_signature_2_18"
path = "src/verify_signature_2_18.rs"

[[bin]]
name = "verify_signature_2_32"
path = "src/verify_signature_2_32.rs"

[[bin]]
name = "sign_message_2_32"
path = "src/sign_message_2_32.rs"

